// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: api/coffee.proto

package coffee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Characteristic int32

const (
	Characteristic_ACIDITY    Characteristic = 0
	Characteristic_AFTERTASTE Characteristic = 1
	Characteristic_AROMA      Characteristic = 2
	Characteristic_BODY       Characteristic = 3
	Characteristic_FLAVOR     Characteristic = 4
	Characteristic_SWEETNESS  Characteristic = 5
)

// Enum value maps for Characteristic.
var (
	Characteristic_name = map[int32]string{
		0: "ACIDITY",
		1: "AFTERTASTE",
		2: "AROMA",
		3: "BODY",
		4: "FLAVOR",
		5: "SWEETNESS",
	}
	Characteristic_value = map[string]int32{
		"ACIDITY":    0,
		"AFTERTASTE": 1,
		"AROMA":      2,
		"BODY":       3,
		"FLAVOR":     4,
		"SWEETNESS":  5,
	}
)

func (x Characteristic) Enum() *Characteristic {
	p := new(Characteristic)
	*p = x
	return p
}

func (x Characteristic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Characteristic) Descriptor() protoreflect.EnumDescriptor {
	return file_api_coffee_proto_enumTypes[0].Descriptor()
}

func (Characteristic) Type() protoreflect.EnumType {
	return &file_api_coffee_proto_enumTypes[0]
}

func (x Characteristic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Characteristic.Descriptor instead.
func (Characteristic) EnumDescriptor() ([]byte, []int) {
	return file_api_coffee_proto_rawDescGZIP(), []int{0}
}

type GetBestTypeCoffeeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Characteristics []Characteristic `protobuf:"varint,1,rep,packed,name=characteristics,proto3,enum=coffee.Characteristic" json:"characteristics,omitempty"`
}

func (x *GetBestTypeCoffeeRequest) Reset() {
	*x = GetBestTypeCoffeeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_coffee_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBestTypeCoffeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBestTypeCoffeeRequest) ProtoMessage() {}

func (x *GetBestTypeCoffeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coffee_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBestTypeCoffeeRequest.ProtoReflect.Descriptor instead.
func (*GetBestTypeCoffeeRequest) Descriptor() ([]byte, []int) {
	return file_api_coffee_proto_rawDescGZIP(), []int{0}
}

func (x *GetBestTypeCoffeeRequest) GetCharacteristics() []Characteristic {
	if x != nil {
		return x.Characteristics
	}
	return nil
}

type GetBestTypeCoffeeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BestCoffee *BestCoffee `protobuf:"bytes,1,opt,name=best_coffee,json=bestCoffee,proto3" json:"best_coffee,omitempty"`
}

func (x *GetBestTypeCoffeeResponse) Reset() {
	*x = GetBestTypeCoffeeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_coffee_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBestTypeCoffeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBestTypeCoffeeResponse) ProtoMessage() {}

func (x *GetBestTypeCoffeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_coffee_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBestTypeCoffeeResponse.ProtoReflect.Descriptor instead.
func (*GetBestTypeCoffeeResponse) Descriptor() ([]byte, []int) {
	return file_api_coffee_proto_rawDescGZIP(), []int{1}
}

func (x *GetBestTypeCoffeeResponse) GetBestCoffee() *BestCoffee {
	if x != nil {
		return x.BestCoffee
	}
	return nil
}

type BestCoffee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gemini     []*Option `protobuf:"bytes,1,rep,name=gemini,proto3" json:"gemini,omitempty"`
	Database   []*Option `protobuf:"bytes,2,rep,name=database,proto3" json:"database,omitempty"`
	Disclaimer string    `protobuf:"bytes,3,opt,name=disclaimer,proto3" json:"disclaimer,omitempty"`
}

func (x *BestCoffee) Reset() {
	*x = BestCoffee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_coffee_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BestCoffee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BestCoffee) ProtoMessage() {}

func (x *BestCoffee) ProtoReflect() protoreflect.Message {
	mi := &file_api_coffee_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BestCoffee.ProtoReflect.Descriptor instead.
func (*BestCoffee) Descriptor() ([]byte, []int) {
	return file_api_coffee_proto_rawDescGZIP(), []int{2}
}

func (x *BestCoffee) GetGemini() []*Option {
	if x != nil {
		return x.Gemini
	}
	return nil
}

func (x *BestCoffee) GetDatabase() []*Option {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *BestCoffee) GetDisclaimer() string {
	if x != nil {
		return x.Disclaimer
	}
	return ""
}

type Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string            `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Details map[string]string `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Option) Reset() {
	*x = Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_coffee_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_api_coffee_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_api_coffee_proto_rawDescGZIP(), []int{3}
}

func (x *Option) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Option) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_coffee_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_coffee_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_coffee_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_coffee_proto protoreflect.FileDescriptor

var file_api_coffee_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x22, 0x5c, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x42, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x52, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x22, 0x50, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x42,
	0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x62, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x6f,
	0x66, 0x66, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x66,
	0x66, 0x65, 0x65, 0x2e, 0x42, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x52, 0x0a,
	0x62, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x22, 0x80, 0x01, 0x0a, 0x0a, 0x42,
	0x65, 0x73, 0x74, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x67, 0x65, 0x6d,
	0x69, 0x6e, 0x69, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x66, 0x66,
	0x65, 0x65, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x67, 0x65, 0x6d, 0x69, 0x6e,
	0x69, 0x12, 0x2a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x2e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x64, 0x69, 0x73, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x72, 0x22, 0x95, 0x01,
	0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x2e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x5d, 0x0a, 0x0e,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x12, 0x0b,
	0x0a, 0x07, 0x41, 0x43, 0x49, 0x44, 0x49, 0x54, 0x59, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x41,
	0x46, 0x54, 0x45, 0x52, 0x54, 0x41, 0x53, 0x54, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x41,
	0x52, 0x4f, 0x4d, 0x41, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x44, 0x59, 0x10, 0x03,
	0x12, 0x0a, 0x0a, 0x06, 0x46, 0x4c, 0x41, 0x56, 0x4f, 0x52, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09,
	0x53, 0x57, 0x45, 0x45, 0x54, 0x4e, 0x45, 0x53, 0x53, 0x10, 0x05, 0x32, 0x69, 0x0a, 0x0d, 0x43,
	0x6f, 0x66, 0x66, 0x65, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x42, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x66, 0x66, 0x65,
	0x65, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x69, 0x63, 0x68, 0x61, 0x72, 0x64, 0x62, 0x65, 0x72, 0x74,
	0x6f, 0x7a, 0x7a, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2d, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65,
	0x2f, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_coffee_proto_rawDescOnce sync.Once
	file_api_coffee_proto_rawDescData = file_api_coffee_proto_rawDesc
)

func file_api_coffee_proto_rawDescGZIP() []byte {
	file_api_coffee_proto_rawDescOnce.Do(func() {
		file_api_coffee_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_coffee_proto_rawDescData)
	})
	return file_api_coffee_proto_rawDescData
}

var file_api_coffee_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_coffee_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_coffee_proto_goTypes = []any{
	(Characteristic)(0),               // 0: coffee.Characteristic
	(*GetBestTypeCoffeeRequest)(nil),  // 1: coffee.GetBestTypeCoffeeRequest
	(*GetBestTypeCoffeeResponse)(nil), // 2: coffee.GetBestTypeCoffeeResponse
	(*BestCoffee)(nil),                // 3: coffee.BestCoffee
	(*Option)(nil),                    // 4: coffee.Option
	(*Error)(nil),                     // 5: coffee.Error
	nil,                               // 6: coffee.Option.DetailsEntry
}
var file_api_coffee_proto_depIdxs = []int32{
	0, // 0: coffee.GetBestTypeCoffeeRequest.characteristics:type_name -> coffee.Characteristic
	3, // 1: coffee.GetBestTypeCoffeeResponse.best_coffee:type_name -> coffee.BestCoffee
	4, // 2: coffee.BestCoffee.gemini:type_name -> coffee.Option
	4, // 3: coffee.BestCoffee.database:type_name -> coffee.Option
	6, // 4: coffee.Option.details:type_name -> coffee.Option.DetailsEntry
	1, // 5: coffee.CoffeeService.GetBestTypeCoffee:input_type -> coffee.GetBestTypeCoffeeRequest
	2, // 6: coffee.CoffeeService.GetBestTypeCoffee:output_type -> coffee.GetBestTypeCoffeeResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_coffee_proto_init() }
func file_api_coffee_proto_init() {
	if File_api_coffee_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_coffee_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetBestTypeCoffeeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_coffee_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetBestTypeCoffeeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_coffee_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BestCoffee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_coffee_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_coffee_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_coffee_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_coffee_proto_goTypes,
		DependencyIndexes: file_api_coffee_proto_depIdxs,
		EnumInfos:         file_api_coffee_proto_enumTypes,
		MessageInfos:      file_api_coffee_proto_msgTypes,
	}.Build()
	File_api_coffee_proto = out.File
	file_api_coffee_proto_rawDesc = nil
	file_api_coffee_proto_goTypes = nil
	file_api_coffee_proto_depIdxs = nil
}
