// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package service

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Coffee struct {
	ID              uuid.UUID
	Specie          string
	Owner           string
	CountryOfOrigin string
	Company         sql.NullString
	Aroma           pgtype.Numeric
	Flavor          pgtype.Numeric
	Aftertaste      pgtype.Numeric
	Acidity         pgtype.Numeric
	Body            pgtype.Numeric
	Sweetness       pgtype.Numeric
}
