// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package provider

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Coffee struct {
	ID              pgtype.UUID
	Specie          string
	Owner           string
	CountryOfOrigin string
	Company         pgtype.Text
	Aroma           float32
	Flavor          float32
	Aftertaste      float32
	Acidity         float32
	Body            float32
	Sweetness       float32
}
