// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package provider

import (
	"database/sql"

	"github.com/google/uuid"
)

type Coffee struct {
	ID              uuid.UUID
	Specie          string
	Owner           string
	CountryOfOrigin string
	Company         sql.NullString
	Aroma           float32
	Flavor          float32
	Aftertaste      float32
	Acidity         float32
	Body            float32
	Sweetness       float32
}
