name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - uses: actions/checkout@v4
      - name: Lint
        run: make lint
          
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Build
      run: make build

  test:
    name: test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - uses: actions/checkout@v4
      - name: Run tests
        run: make test
      - name: Upload coverage in Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out

  push-docker-image:
    name: push docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: push to github registry
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: type-coffee-api
          registry: ghcr.io
          addLatest: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
